version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecostystem: "npm"
    directory: "/web-src/"
    schedule:
      interval: "weekly"
